[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
send_message = '0x04c9a2b031847734f202ff99c5de01cdaebe83a74172736c23ef465e169e1145'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]